name: RPC test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag version'     
        required: true
        default: '4.9.0'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2

    - run: wget -q https://github.com/AstarNetwork/Astar/releases/download/v${{ github.event.inputs.tag }}/astar-collator-${{ github.event.inputs.tag }}-ubuntu-x86_64.tar.gz

    - run: tar -xvf astar-collator-*-ubuntu-x86_64.tar.gz
    
    - run: chmod +x ./astar-collator
